In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.DataFrame({
    'Age' :[25,24,26,28,23,21,20],
    'Exp' : [5,6,7,8,4,5,4],
    'Salary' : [50000,75000,45000,65000,74000,45000,65000]
})
df

   Age  Exp  Salary
0   25    5   50000
1   24    6   75000
2   26    7   45000
3   28    8   65000
4   23    4   74000
5   21    5   45000
6   20    4   65000

In [4]:
df.describe()

             Age       Exp        Salary
count   7.000000  7.000000      7.000000
mean   23.857143  5.571429  59857.142857
std     2.794553  1.511858  13043.881981
min    20.000000  4.000000  45000.000000
25%    22.000000  4.500000  47500.000000
50%    24.000000  5.000000  65000.000000
75%    25.500000  6.500000  69500.000000
max    28.000000  8.000000  75000.000000

In [5]:
sc = StandardScaler()

scaled_df = pd.DataFrame(sc.fit_transform(df), columns=df.columns)

In [7]:
scaled_df

        Age       Exp    Salary
0  0.441726 -0.408248 -0.816239
1  0.055216  0.306186  1.253933
2  0.828236  1.020621 -1.230274
3  1.601257  1.735055  0.425864
4 -0.331295 -1.122683  1.171126
5 -1.104315 -0.408248 -1.230274
6 -1.490826 -1.122683  0.425864

In [8]:
scaled_df.describe()

                Age           Exp        Salary
count  7.000000e+00  7.000000e+00  7.000000e+00
mean  -2.220446e-16  1.903239e-16  1.586033e-16
std    1.080123e+00  1.080123e+00  1.080123e+00
min   -1.490826e+00 -1.122683e+00 -1.230274e+00
25%   -7.178049e-01 -7.654655e-01 -1.023257e+00
50%    5.521576e-02 -4.082483e-01  4.258641e-01
75%    6.349813e-01  6.634035e-01  7.984951e-01
max    1.601257e+00  1.735055e+00  1.253933e+00

In [9]:
scaled_df['Age'].mean()

-2.220446049250313e-16